### ISSUE TITLE
Feature - Develop API Gateway Service

### ISSUE THREAD

**Issue by rajdeepc2792** [airavata-courses/neo#13]
API Gateway service as planned will be a service listening for all the HTTP based calls from UI and redirect them to micro-service as required.

**Comment by niravraje** [comment]
With 4ce8146, data processor route added will send query input parameters to data-processing service via gRPC. 
Base64 encoded image being returned from data-processing service. 
Current query parameters expected from the client side are as below (with sample format):

- year (eg: "2021")
- month (eg: "12")
- day (eg: "11")
- hour (eg: "02")
- minute (eg: "55")
- feature (eg: "reflectivity", "velocity", "cross_correlation_ratio" etc. & these are fixed constants) 
- station (eg: "KLVX")

Let me know in case there are any changes to above input query parameters.

**Comment by niravraje** [comment]
Pushed the Docker image for the gateway service to neoairavataproject repository. I will test the gRPC communication between gateway and data processor service using docker-compose.
