### ISSUE TITLE
Feature - Develop DB Service

### ISSUE THREAD

**Issue by rajdeepc2792** [airavata-courses/neo#15]
A Database Service will be a service interacting with DB to fetch and persist data whenever demanded by other service.
Setting up DB and maintaining schema structure will be done through this service only using ORM/ODM.

Tentative Decision - 
- Database to be used is MongoDB

**Comment by niravraje** [comment]
@rajdeepc2792 @shanki07 
Given our plan on implementing our DB service in Python, found some options for ORM/ODM tools listed in PyMongo's documentation. [Link](https://pymongo.readthedocs.io/en/stable/tools.html)
Most popular one I found was [PyMODM](https://github.com/mongodb/pymodm) maintained by MongoDB but it seems they no longer support that project. Other options seem to have less support too, hence a bit skeptical about these tools.
Thinking about skipping use of ODM and directly going with the official PyMongo driver.
If we have decided on NoSQL, I guess MongoDB would be our top choice anyway.
What do you think?
(If we want to stick with an ODM for the flexibility, creating the DB service in Node.js and using Mongoose is an alternative)
