### ISSUE TITLE
Feature - Data Ingestion Service

### ISSUE THREAD

**Issue by rajdeepc2792** [airavata-courses/neo#18]
As Planned, data ingestion service will be fetching data from external weather data service, currently NEXRAD Data, whenever demanded.
It may also have a way to handle real time data notifications(Not Required)

**Comment by niravraje** [comment]
Hi @rajdeepc2792 , since we are handling data ingestion in our data processing microservice, can we update this issue to act as a sub-task of #19 instead of being a "Feature"?

**Comment by shanki07** [comment]
Closing this issue as discussed and decided by the team to have a single service for fetching and processing data.
