### ISSUE TITLE
Create Napkin Diagram

### ISSUE THREAD

**Issue by niravraje** [airavata-courses/neo#2]
Use tools like Draw.io

**Comment by shanki07** [comment]
Please find the attached image for the napkin diagram. Feedbacks are most welcome.![image](https://user-images.githubusercontent.com/9477137/150896119-263f3839-ea19-422b-a0fc-75775ea1049c.png)

**Comment by rajdeepc2792** [comment]
@shanki07 , Good work.
Some concerns:-
- As discussed during planning, we decided to provide an example of "Open Weather Data" like NEXRAD, please try to put it in there.
- We have an idea that parameters will be more than only date for selection, so you can use parameters as:-
          - Radar-Station
          - Date & Time
          - Property(Let's say reflectivity)
          Perhaps we should use these.
- In the Visualization window, if we can also add map with land and sea visible, here it feels like all the representation is weather data representation without mapping it on Earth Map.

Please feel free to disagree on the concerns.

@niravraje , Do you agree?

**Comment by niravraje** [comment]
@shanki07 Looks simple and good! 
I agree with @rajdeepc2792's suggestions. 
I had initially also thought of having a box/container around "parameter selection" and "visualization" denoting our client-side. But this looks good as well and serves the purpose.

Some sample user icons we might want to use:

![user-icon3](https://user-images.githubusercontent.com/35288428/151044725-b7a64535-201b-4948-b28a-f1ec2d86b766.png)
![user-icon2](https://user-images.githubusercontent.com/35288428/151044727-8708b4a0-a8b5-4a41-a68b-554c920af9ae.png)
![user-icon1](https://user-images.githubusercontent.com/35288428/151044728-2a7a0815-7170-453e-ba25-74995f613469.png)

**Comment by shanki07** [comment]
![Napkin 2 drawio](https://user-images.githubusercontent.com/9477137/152917463-18153b11-78e5-4181-b2a1-ab780ac26719.png)

**Comment by niravraje** [comment]
@rajdeepc2792 @shanki07 Just wanted to update our napkin diagram as the images were a bit blurry. Also changed a few icons here and there which I found on draw.io. Could you both review and LMK if this looks good?

![Neo Napkin Diagram 2](https://user-images.githubusercontent.com/35288428/153308256-fe6cc19f-8f89-490d-b179-f03ea1810a59.png)
