### ISSUE TITLE
Containerize API gateway with Docker and configure image build in docker-compose

### ISSUE THREAD

**Issue by niravraje** [airavata-courses/neo#21]
For #13, create a Dockerfile for building a Docker image and test connection on localhost of host machine.
Configure the build of this Dockerfile in docker-compose YAML file which contains instructions for spinning up and connecting all other containers.

**Comment by rajdeepc2792** [comment]
@niravraje , I have created the docker-compose for the BE services which I own as feature development. I will be pushing it in a while and will link to this issue. Adding myself as an assignee as well.

**Comment by rajdeepc2792** [comment]
@niravraje , created dockerhub account for publishing images:-
